"""unique concept per file

Revision ID: 61d7f06bd4a8
Revises: 459a87bcbf8a
Create Date: 2025-10-28 15:18:09.983425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d7f06bd4a8'
down_revision: Union[str, Sequence[str], None] = '459a87bcbf8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_concepts_file_id', 'concepts', ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_concepts_file_id', 'concepts', type_='unique')
    # ### end Alembic commands ###
